  version: '3'
  
  services:
    flask-app:
      image: moshaher/flaskrepo:flaskmysql

      build: ./app
      links:
        - mysql
      ports:
        - "8080:8080"
      depends_on: 
        - mysql
    
    mysql:
      image: moshaher/flaskrepo:flaskmysql
      ports:
        - '32000:3306'
      environment:    
        MYSQL_ROOT_PASSWORD: root123
      volumes:
        - ./mysql/init.sql:/docker-entrypoint-initdb.d/db.sql
        - ./data:/var/lib/mysql
      
