# Generated by Django 5.0.6 on 2024-06-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mppr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaName', models.CharField(max_length=50)),
                ('areaSqm', models.FloatField(max_length=50)),
                ('work', models.CharField(max_length=50)),
                ('manpower', models.CharField(max_length=25)),
                ('quantity', models.SmallIntegerField()),
                ('startdate', models.DateField()),
                ('finishdate', models.DateField()),
                ('duration', models.SmallIntegerField()),
                ('rateHourPerSqm', models.FloatField()),
            ],
        ),
    ]
