# Generated by Django 5.0.6 on 2024-06-29 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpprapp', '0007_alter_mppr_finishdate_alter_mppr_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mppr',
            name='finishdate',
            field=models.DateField(blank=True, default='0/0/0', null=True),
        ),
        migrations.AlterField(
            model_name='mppr',
            name='startdate',
            field=models.DateField(blank=True, default='0/0/0', null=True),
        ),
    ]
