# Generated by Django 5.0.6 on 2024-06-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpprapp', '0009_alter_mppr_finishdate_alter_mppr_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mppr',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mppr',
            name='finishdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mppr',
            name='startdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
