# Generated by Django 5.0.6 on 2024-06-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpprapp', '0010_alter_mppr_duration_alter_mppr_finishdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mppr',
            name='rateHourPerSqm',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
