  version: '3'
  
  services:
    flask-app:
      image: moshaher/flaskrepo:flask

      build: ./app

      ports:
        - "8080:5000"
      depends_on: 
        - db

    
    db:
      image: moshaher/flaskrepo:8.1
      restart: always
      environment:    
        MYSQL_ROOT_PASSWORD: root123
        MYSQL_DATABASE: reldb1
        MYSQL_USER: flask
        MYSQL_PASSWORD: mysql

      ports:
        - "32000:3306"
  
      volumes:
        - ./db_data:/var/lib/mysql

  volumes:
    db_data:

      
