# Generated by Django 5.0.6 on 2024-06-27 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punchlistapp', '0002_alter_punchlist_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punchlist',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
